# Generated by Django 4.2.16 on 2024-09-26 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_alter_book_cover_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='cover_image',
            new_name='local_image',
        ),
        migrations.AddField(
            model_name='book',
            name='external_image',
            field=models.URLField(blank=True),
        ),
    ]
