# Generated by Django 4.2.16 on 2024-09-23 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
