# Generated by Django 4.2.16 on 2024-09-23 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn', models.CharField(max_length=20, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('pub_date', models.DateField()),
                ('author', models.CharField(max_length=255)),
                ('price_sales', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
